name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  check:
    uses: pleme-io/substrate/.github/workflows/cargo-ci.yml@main
    with:
      build-targets: ".#default"
    secrets: inherit
